// Generated by ReScript, PLEASE EDIT WITH CARE


var OnHistoryStateUpdated = {};

var WebNavigation = {
  OnHistoryStateUpdated: OnHistoryStateUpdated
};

var Tabs = {};

export {
  WebNavigation ,
  Tabs ,
}
/* No side effect */
