// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Alert(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "bg-yellow-50 p-4 rounded-lg"
            }, React.createElement("div", {
                  className: "flex"
                }, React.createElement("div", {
                      className: "flex-shrink-0"
                    }, React.createElement("svg", {
                          className: "h-5 w-5 text-yellow-400",
                          fill: "none",
                          stroke: "currentColor",
                          strokeWidth: "1.5",
                          viewBox: "0 0 24 24",
                          xmlns: "http://www.w3.org/2000/svg"
                        }, React.createElement("path", {
                              d: "M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z",
                              strokeLinecap: "round",
                              strokeLinejoin: "round"
                            }))), React.createElement("div", {
                      className: "ml-3"
                    }, React.createElement("p", {
                          className: "text-sm text-yellow-700"
                        }, children))));
}

var make = Alert;

export {
  make ,
}
/* react Not a pure module */
