// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as GroupIcon from "./GroupIcon.bs.js";

function Header(Props) {
  return React.createElement("div", {
              className: "flex items-center gap-2 text-slate-800 "
            }, React.createElement(GroupIcon.make, {
                  className: "w-8 h-8"
                }), React.createElement("h2", {
                  className: "text-xl font-semibold"
                }, "Mubi Watch Party"));
}

var make = Header;

export {
  make ,
}
/* react Not a pure module */
