// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Webapi__Dom__Document from "rescript-webapi/src/Webapi/Dom/Webapi__Dom__Document.bs.js";

function getPageTitle(param) {
  var doc = Webapi__Dom__Document.asHtmlDocument(document);
  if (doc !== undefined) {
    return Caml_array.get(Caml_option.valFromOption(doc).title.split("|"), 0).trim();
  } else {
    return Pervasives.failwith("No document");
  }
}

function getPageUrl(param) {
  return window.location.href;
}

function getVideoEl(param) {
  return Caml_option.nullable_to_opt(document.querySelector(".video-player video"));
}

function getNestedControlEl(param) {
  return Caml_option.nullable_to_opt(document.querySelector("div[title='Enter full screen']"));
}

export {
  getPageTitle ,
  getPageUrl ,
  getVideoEl ,
  getNestedControlEl ,
}
/* Webapi__Dom__Document Not a pure module */
